# Test05: test code for Batch Martix Calculation

# Preparation 

## Preparation of google drive (if required)

In [2]:
#　colaboraory用: Google drive をマウントする
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
# colaboratory用: フォルダを移る
%cd "drive/My Drive/Colab Notebooks"

/content/drive/My Drive/Colab Notebooks


フォルダは自分の指定のものに変更して下さい。

In [4]:
%cd "ctorch211217/MiniCTorch_Prototype/notebook"

/content/drive/My Drive/Colab Notebooks/ctorch211217/MiniCTorch_Prototype/notebook


## Installation of MiniCTorch

In [ ]:
! pip install git+https://github.com/kojima-r/MiniCTorch_Prototype.git

## C++コードをコンパイル、実行

In [ ]:
! cat ./test/test05_batch.cpp


#include "minictorch.hpp"

using namespace std;

void print_shape(Tensor x, string ss )
{
    auto s=x.shape();
    cout<<ss<<" shape (";
    for(int i=0;i<s.size();i++){
        cout<<s[i]<<",";
    }
    cout<<")"<<endl;
}

void test01()
{
    Tensor a=
            {{{1, 2, 3},
            {4, 5, 6},
            {7, 8, 9}},
            {{1, 2, 3},
            {4, 5, 6},
            {7, 8, 9}}};
    Tensor b=
            {{{1, 2, 3},
            {4, 5, 6},
            {7, 8, 9}},
            {{1, 2, 3},
            {4, 5, 6},
            {7, 8, 9}}};
    Tensor c({2,3,3});
    
    for (int i = 0; i < 2; ++i) {
        for (int j = 0; j < 3; ++j) {
            for (int k = 0; k < 3; ++k) {
                a[i, j,k] = 1;
                b[i, j,k] = 1;
            }
        }
    }
    c=a+b;
    cout<<"a"<<a<<endl;
    cout<<"b"<<b<<endl;
    cout<<"c"<<c<<endl;
    const auto& d = c.shape();
    cout << "Dim size: " << d.size() <<endl;
    //for(int i=0;i<d.size();i++){
    //    cou

In [5]:
C_SRC = './test/test05_batch.cpp'
C_OPT = '-I ./MiniCTorch_Prototype/src -I ./xtensor/include -I ./xtensor-blas/include -I ./xtl/include -I ./json/include '
C_OUT = './test/test05_batch'
!echo "SRC = "$C_SRC
!echo "OPT = "$C_OPT
!echo "OUT = "$C_OUT
!g++ -std=c++14 $C_SRC $C_OPT -lcblas -o $C_OUT

SRC = ./test/test05_batch.cpp
OPT = -I ./MiniCTorch_Prototype/src -I ./xtensor/include -I ./xtensor-blas/include -I ./xtl/include -I ./json/include
OUT = ./test/test05_batch


In [7]:
!./test/test05_batch

b{{ 1.,  2.,  3.},
 { 4.,  5.,  6.},
 { 4.,  5.,  6.},
 { 7.,  8.,  9.}}
bb{{{ 1.,  2.,  3.}},
 {{ 4.,  5.,  6.}},
 {{ 4.,  5.,  6.}},
 {{ 7.,  8.,  9.}}}
z{{{ 1.,  2.,  3.},
  { 1.,  2.,  3.}},
 {{ 4.,  5.,  6.},
  { 4.,  5.,  6.}},
 {{ 4.,  5.,  6.},
  { 4.,  5.,  6.}},
 {{ 7.,  8.,  9.},
  { 7.,  8.,  9.}}}
==
a{{{  1.,   2.,   3.,   4.},
  {  4.,   5.,   6.,   7.},
  {  7.,   8.,   9.,  10.}},
 {{  1.,   2.,   3.,   4.},
  {  4.,   5.,   6.,   7.},
  {  7.,   8.,   9.,   9.}}}
b{{ 1.,  2.,  3.},
 { 4.,  5.,  6.},
 { 4.,  5.,  6.},
 { 7.,  8.,  9.}}
c{{{  49.,   59.,   69.},
  {  97.,  119.,  141.},
  { 145.,  179.,  213.}},
 {{  49.,   59.,   69.},
  {  97.,  119.,  141.},
  { 138.,  171.,  204.}}}
==
va_grad{{{  6.,  15.,  15.,  24.},
  {  6.,  15.,  15.,  24.},
  {  6.,  15.,  15.,  24.}},
 {{  6.,  15.,  15.,  24.},
  {  6.,  15.,  15.,  24.},
  {  6.,  15.,  15.,  24.}}}
vb_grad{{{ 12.,  12.,  12.},
  { 15.,  15.,  15.},
  { 18.,  18.,  18.},
  { 21.,  21.,  21.}},
 {{ 12.,  12

## Installation of MiniCTorch

In [8]:
! pip install lark-parser

     |████████████████████████████████| 103 kB 25.7 MB/s 


In [9]:
import sys
sys.path.append( "../")
import numpy as np
import torch
import minictorch

In [ ]:
a= np.array( [[[1, 2, 3, 4],
            [4, 5, 6, 7],
            [7, 8, 9,10]],
            [[1, 2, 3, 4],
            [4, 5, 6,7],
            [7, 8, 9,9]]])
b=np.array([[1, 2, 3],
   [4, 5, 6],
   [4, 5, 6],
   [7, 8, 9]])

In [ ]:
print(a.shape)
print(b.shape)

(2, 3, 4)
(4, 3)


## ニューラルネットの定義

In [10]:
class Net(torch.nn.Module):
   def __init__(self, a):
      super(Net, self).__init__()
      self.x = a

   def forward(self,y):
      z = torch.matmul(self.x, y)
      return z

##プロジェクト名、作業フォルダ、JSONファイル名の設定

In [11]:
project = "test05"
folder = "./test"
json_path = folder + '/' + project +'.json'

In [12]:
! mkdir -p test

## 計算グラフをJSONファイルに出力する


In [13]:
def generate_json( json_path, input_x, input_y ):
   model = Net( input_x )
   model.eval()
   with torch.no_grad():
      minictorch.trace( model, input_y, json_path )
   return model

In [14]:
a=np.array( [[[1., 2, 3, 4],[4, 5, 6, 7],[7, 8, 9,10]],
            [[1, 2, 3, 4],[4, 5, 6, 7],[7, 8, 9, 9]]] )
b=np.array([[1., 2, 3],[4, 5, 6],[4, 5, 6],[7, 8, 9]])
x = torch.tensor( a )
y = torch.tensor( b , requires_grad=True)
print("a",a)
print("b",b)
model = generate_json( json_path, x, y )

a [[[ 1.  2.  3.  4.]
  [ 4.  5.  6.  7.]
  [ 7.  8.  9. 10.]]

 [[ 1.  2.  3.  4.]
  [ 4.  5.  6.  7.]
  [ 7.  8.  9.  9.]]]
b [[1. 2. 3.]
 [4. 5. 6.]
 [4. 5. 6.]
 [7. 8. 9.]]


## JSONファイルをC++コードに変換する

In [15]:
minictorch.convert_all( project, folder, model, json_path, y, {"inp_data":y}, code="test" )

[JSON] ./test/test05.json
{'name': 'Net/4', 'op': 'prim::Constant', 'in': [], 'output_id': 0, 'shape': [2, 3, 4], 'constant_value': [1.0, 2.0, 3.0, 4.0, 4.0, 5.0, 6.0, 7.0, 7.0, 8.0, 9.0, 10.0, 1.0, 2.0, 3.0, 4.0, 4.0, 5.0, 6.0, 7.0, 7.0, 8.0, 9.0, 9.0], 'out': [2], 'sorted_id': 0}
[PARAM] ./test/test05_param.cpp
{'name': 'Net/4', 'op': 'prim::Constant', 'in': [], 'output_id': 0, 'shape': [2, 3, 4], 'constant_value': [1.0, 2.0, 3.0, 4.0, 4.0, 5.0, 6.0, 7.0, 7.0, 8.0, 9.0, 10.0, 1.0, 2.0, 3.0, 4.0, 4.0, 5.0, 6.0, 7.0, 7.0, 8.0, 9.0, 9.0], 'out': [2], 'sorted_id': 0}
{'name': 'input/y', 'op': 'IO Node', 'in': [], 'output_id': 0, 'shape': [4, 3], 'out': [2], 'sorted_id': 1}
{'name': 'Net/5', 'op': 'aten::matmul', 'in': [0, 1], 'output_id': 0, 'shape': [2, 3, 3], 'out': [3], 'sorted_id': 2}
{'name': 'output/output.1', 'op': 'IO Node', 'in': [2], 'output_id': 0, 'shape': [2, 3, 3], 'out': [], 'sorted_id': 3}
[CPP]  ./test/test05.cpp
[MAKE] ./test/Makefile


## pythonコードを実行する

In [16]:
# check code
model.train()
z = model( y )
print(z)
z.sum().backward()
print(x.grad)
print(y.grad)

tensor([[[ 49.,  59.,  69.],
         [ 97., 119., 141.],
         [145., 179., 213.]],

        [[ 49.,  59.,  69.],
         [ 97., 119., 141.],
         [138., 171., 204.]]], dtype=torch.float64,
       grad_fn=<UnsafeViewBackward0>)
None
tensor([[24., 24., 24.],
        [30., 30., 30.],
        [36., 36., 36.],
        [41., 41., 41.]], dtype=torch.float64)


## C++コードをコンパイル、実行

In [17]:
C_SRC = './test/test05.cpp ./test/test05_param.cpp'
C_OPT = '-I ./MiniCTorch_Prototype/src -I ./xtensor/include -I ./xtensor-blas/include -I ./xtl/include -I ./json/include'
C_OUT = './test/test05'
!echo "SRC = "$C_SRC
!echo "OPT = "$C_OPT
!echo "OUT = "$C_OUT
!g++ -std=c++14 $C_SRC $C_OPT -lcblas -o $C_OUT

SRC = ./test/test05.cpp ./test/test05_param.cpp
OPT = -I ./MiniCTorch_Prototype/src -I ./xtensor/include -I ./xtensor-blas/include -I ./xtl/include -I ./json/include
OUT = ./test/test05


In [18]:
! ./test/test05

### forward computation ...
{{{  49.,   59.,   69.},
  {  97.,  119.,  141.},
  { 145.,  179.,  213.}},
 {{  49.,   59.,   69.},
  {  97.,  119.,  141.},
  { 138.,  171.,  204.}}}
### backward computation ...
input_grad{{{ 12.,  12.,  12.},
  { 15.,  15.,  15.},
  { 18.,  18.,  18.},
  { 21.,  21.,  21.}},
 {{ 12.,  12.,  12.},
  { 15.,  15.,  15.},
  { 18.,  18.,  18.},
  { 20.,  20.,  20.}}}
