In [1]:
#　colaboraory用: Google drive をマウントする
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [2]:
# colaboratory用: フォルダを移る
%cd "drive/My Drive/Colab Notebooks"

/content/drive/My Drive/Colab Notebooks


フォルダは自分の指定のものに変更してね。

In [3]:
%cd "ctorch210824/MiniCTorch_Prototype"

/content/drive/My Drive/Colab Notebooks/ctorch210824/MiniCTorch_Prototype


In [4]:
!g++ -std=c++14 ./src/broadcast_check.cpp -lcblas -I ../../ctorch/lib -o ./bin/broadcast_check

In [5]:
!./bin/broadcast_check

a{{ 0.,  0.,  0.},
 { 0.,  0.,  0.},
 { 0.,  0.,  0.}}
b{ 0.,  1.,  2.}
c{{ 0.},
 { 1.},
 { 2.}}
--- brodcat check -----------
a{{ 0.,  0.,  0.},
 { 0.,  0.,  0.},
 { 0.,  0.,  0.}}
b{ 0.,  1.,  2.}
a shape (3,3,)
b shape (3,)
n_dim=2
na 3,3,
nb 1,3,
equal=1 eq1=1 other=0
shape 3,3
shape (3,3,)
broadcast check status=1
try type=1
a+b {{ 0.,  1.,  2.},
 { 0.,  1.,  2.},
 { 0.,  1.,  2.}}
--- brodcat check -----------
a{{ 0.,  0.,  0.},
 { 0.,  0.,  0.},
 { 0.,  0.,  0.}}
b{{ 0.},
 { 1.},
 { 2.}}
a shape (3,3,)
b shape (3,1,)
n_dim=2
na 3,3,
nb 3,1,
equal=1 eq1=1 other=0
shape 3,3
shape (3,3,)
broadcast check status=1
try type=1
a+b {{ 0.,  0.,  0.},
 { 1.,  1.,  1.},
 { 2.,  2.,  2.}}
--- brodcat check -----------
a{ 0.,  1.,  2.,  3.}
b{{ 0.},
 { 1.},
 { 2.}}
a shape (4,)
b shape (3,1,)
n_dim=2
na 1,4,
nb 3,1,
equal=0 eq1=2 other=0
shape 3,4
shape (3,4,)
broadcast check status=1
try type=1
a+b {{ 0.,  1.,  2.,  3.},
 { 1.,  2.,  3.,  4.},
 { 2.,  3.,  4.,  5.}}
a5{{ 0.,  0.,  0.},
 { 0

Broadcast test

In [ ]:
import numpy as np

a = np.zeros((3, 3), np.int)
print(a)

b = np.arange(3)
print(b)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
[0 1 2]


In [ ]:
np.broadcast_to(b,(3,3))

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [ ]:
c=b.reshape(3,1)

In [ ]:
c

array([[0],
       [1],
       [2]])

In [ ]:
np.broadcast_to(c,(3,3))

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]])

In [ ]:
a+b

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [ ]:
a+c

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]])

In [ ]:
b+c

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [ ]:
d = np.arange(4)
print(d)

[0 1 2 3]


In [ ]:
d+c

array([[0, 1, 2, 3],
       [1, 2, 3, 4],
       [2, 3, 4, 5]])

In [ ]:
c.shape

(3, 1)

In [ ]:
np.broadcast_to(c,(3,4))

array([[0, 0, 0, 0],
       [1, 1, 1, 1],
       [2, 2, 2, 2]])

In [ ]:
np.broadcast_to(d,(3,4))

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

In [ ]:
a5 = np.zeros((4, 3), dtype=np.int)
print(a5)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [ ]:
b5 = np.arange(6).reshape(2, 3)
print(b5)

[[0 1 2]
 [3 4 5]]


In [ ]:
a5+b5

ValueError: ignored

In [ ]:
try:
  print(a5+b5)
except:
  print("broadcast error. shapes", a.shape, ",",  b.shape)

broadcast error. shapes (3, 3) , (3,)


In [ ]:
a_dim = a.ndim
b_dim = b.ndim
print("ndim",a_dim,b_dim)
n_dim = max(a.ndim, b.ndim)
print("n_dim", n_dim)

ndim 2 1
n_dim 2


In [ ]:
na = np.ones(a_dim,dtype=np.int)

In [ ]:
def check_shape1(a,n_dim):
  na = np.ones(a_dim,dtype=np.int)
  inc = n_dim - a.ndim
  for i in range(a.ndim):
    na[inc+i] = a.shape[i]
  return na

In [ ]:
na=check_shape1(a5,2)
nb=check_shape1(b5,2)
print(na,nb)

[4 3] [2 3]


In [ ]:
try:
  c5=a5+b5
except:
   print("broadcast error. shapes", a5.shape, ",",  b5.shape)

broadcast error. shapes (4, 3) , (2, 3)


In [ ]:
na=check_shape1(a,2)
nb=check_shape1(b,2)
print(na,nb)

[3 3] [1 3]


In [ ]:
def check_broadcast( a, b ):

  import numbers
  def is_scalar(a):
    return isinstance( a, numbers.Number )

  def check_shape( a, n_dim ):
    na = np.ones( n_dim, dtype=np.int )
    inc = n_dim - a.ndim
    for i in range(a.ndim):
      na[i+inc] = a.shape[i]
    return na

  """
  try:
    c = a + b
    #print(c
  except:
    print("broadcast error. shapes=", a.shape, ",",  b.shape)
    return 0
  """

  ns = 0
  if is_scalar(a):  ns += 1
  if is_scalar(b):  ns += 1
  if( ns > 0 ): 
    print("scalar =",ns)
    return 2

  #n_dim = a.ndim
  #if( n_dim < b.ndim ):  n_dim = b.ndim
  n_dim = max( a.ndim, b.ndim )
  na = check_shape( a, n_dim )
  nb = check_shape( b, n_dim )
  print("dimension", n_dim,na,nb)

  ne = 0
  n1 = 0
  n2 = 0
  for i in range(n_dim):
    if na[i] == 1:  
      n1 += 1
    elif nb[i] == 1:  
      n1 += 1
    elif na[i] == nb[i]:
      ne += 1
    else:
      #print("broadcast mismatch dimension no.",i)
      n2 += 1
  print("equal=",ne," eq1 =",n1," other =",n2)
  status = 1;
  if( ne == n_dim ):   
    pass
  elif ( (ne+n1) == n_dim ):  
    pass
  elif ( ((n1+n2) == n_dim) & (n2==1) ):  
    pass
  else:
    print("broadcast error. shapes=", a.shape, ",",  b.shape)
    status = 0
  print("status =",status)
  return status

In [ ]:
check_broadcast(a,b)

dimension 2 [3 3] [1 3]
equal= 1  eq1 = 1  other = 0
status = 1


1

In [ ]:
check_broadcast(a,c)

dimension 2 [3 3] [3 1]
equal= 1  eq1 = 1  other = 0
status = 1


1

In [ ]:
check_broadcast(d,c)

dimension 2 [1 4] [3 1]
equal= 0  eq1 = 2  other = 0
status = 1


1

In [ ]:
check_broadcast(a5,b5)
print(c2)

dimension 2 [4 3] [2 3]
equal= 1  eq1 = 0  other = 1
broadcast error. shapes= (4, 3) , (2, 3)
status = 0
1


In [ ]:
a5+b5

ValueError: ignored

In [ ]:
e=1
check_broadcast(a,e)

scalar = 1


1

In [ ]:
a+e

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])